layout_spectrum: 0.589017526479438
typography_spectrum: 0.8864992512390018
color:
  brandStrength: 0.5743682635948062
  lightness: 0.8840017972979695
  saturation: 0.4513153175357729
  rhythmicContrast: 0.3481470034457743
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: chronicdisorder
